### ISSUE TITLE
Parry cooldown config option isn't properly applied

### ISSUE THREAD

**Issue by Void-0000** [Xires87/SwordParry#4]
When parrying projectiles, the parry cooldown option appears to be completely ignored, and set to a fixed value instead. When parrying melee attacks, the setting is correctly applied, unless it's too small (for example, 0 or 1), at which point a "minimum" value seems to be used instead (possibly the same as the projectile's fixed value).

Tested this on fabric 1.20.1, with no mods other than Cloth Config, Fabric API, and Sword Parry, using a sword to parry.

**Comment by Xires87** [comment]
Fixed in Sword Parry 4.2.0.
Thanks for reporting this issue and for a clear explanation of the problem :)
