### ISSUE TITLE
Allow parrying with arbitrary non-tool items

### ISSUE THREAD

**Issue by Void-0000** [Xires87/SwordParry#5]
Some mods, like Tetra, have tools and weapons that for some reason don't inherit from the vanilla ToolItem class, which means they won't be able to parry with this mod.

A config setting to manually add a list of items (or tags) to the mod's item types would solve this, but I think allowing any item with an attack speed attribute to parry (with block/parry cooldowns proportional to its attack speed, maybe with a multiplier config setting for each) would work better, as it would cover more or less every item someone is likely to want to parry with, in any mod, while allowing modded weapons with faster attack speeds to automatically have a lower parry cooldown, which I think makes sense.

**Comment by Xires87** [comment]
Done
