### ISSUE TITLE
custom datapack not working with tetra (synatra connector)

### ISSUE THREAD

**Issue by TerravoltPrime** [Xires87/SwordParry#7]
[tetra_parry_datapack.zip](https://github.com/Xires87/SwordParry/files/15144127/tetra_parry_datapack.zip)
I have no Idea what went wrong with it.

**Comment by Xires87** [comment]
```json
{
  "parryAttributes": "sword",
  "items": [
    "tetra:modular_sword",
    "tetra:modular_shortblade"
  ]
}
```

`tetra:modular_shortblade` doesn't exist, there is no such item.
Just remove it and everything will be ok.

And remember that setting parry attributes for items doesn't enable parrying with them (i know it's not intuitive, but it was the easiest and fastest way for me to implement).

To be able to parry with modular sword you have to add it to ["items_can_parry"](https://github.com/Xires87/SwordParry/blob/master/src/main/resources/data/frycparry/tags/items/items_can_parry.json) tag (`data/frycparry/tags/items/items_can_parry.json`)
